### ISSUE TITLE
Ran into critical error when attempting to build

### ISSUE THREAD

**Issue by kobus-v-schoor** [EntelectChallenge/2022-Arctica#20]
Ran into the following error when attempting to place a lumber mill (not the first on the map)

```
[ERROR] [Core]: Failed to run GameRunLoop with error: Object reference not set to an instance of an object.
[DEBUG] [Core]:    at Engine.Services.WorldStateService.UpdateTerritory(BotObject bot, List`1 newTerritoryNodes) in /home/runner/work/2022-Arctica/2022-Arctica/game-engine/Engine/Services/WorldStateService.cs:line 257
   at Engine.Handlers.Actions.BuildActionHandler.ProcessActionComplete(Node node, List`1 playerActions) in /home/runner/work/2022-Arctica/2022-Arctica/game-engine/Engine/Handlers/Actions/BuildActionHandler.cs:line 89
   at Engine.Services.EngineService.SimulateTickForBots(IList`1 bots) in /home/runner/work/2022-Arctica/2022-Arctica/game-engine/Engine/Services/EngineService.cs:line 344
   at Engine.Services.EngineService.ProcessGameTick() in /home/runner/work/2022-Arctica/2022-Arctica/game-engine/Engine/Services/EngineService.cs:line 189
   at Engine.Services.EngineService.GameRunLoop() in /home/runner/work/2022-Arctica/2022-Arctica/game-engine/Engine/Services/EngineService.cs:line 79
   at Engine.Services.SignalRService.<Startup>b__7_1(Task task) in /home/runner/work/2022-Arctica/2022-Arctica/game-engine/Engine/Services/SignalRService.cs:line 119
[ERROR] [Shutdown]: Shutting down due to a critical error
[ERROR] [Shutdown]: Shutting down before a winner was found. Informing the runner.
[ERROR] [Connections]: Engine informed of Disconnect. Reason: Shutdown called before a winner was found.
 Disconnecting all clients and stopping

```

**Comment by kobus-v-schoor** [comment]
Fixed in https://github.com/EntelectChallenge/2022-Arctica/releases/tag/2022.2.2
